<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXch9dwr\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXch9dwr/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXch9dwr.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXch9dwr\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXch9dwr\appProdProjectContainer([
    'container.build_hash' => 'Xch9dwr',
    'container.build_id' => '4ca074f6',
    'container.build_time' => 1567995597,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXch9dwr');
